### ISSUE TITLE
Compatibility with Python3 ?

### ISSUE THREAD

**Issue by Inventor-Mentor** [rougier/atb-python#4]
Hello,

Thank you very much indeed for contributing and sharing atb-python on GitHub.

Could you please confirm that atb-python works (or worked) for you with Python 3 (ideally also in a 32-bit [Linux] environment)?

My environment is as Raspberry Pi 4 computer operating with a Raspbian Buster Linux distribution kernel 5.10.103-v7l+ armv7l GNU/Linux (32-bit user-space addresses) with Python 3.7.3.

After cloning your repository and converting the files in ./atb/ to Python 3 via
2to3 -w *.py
and uncommenting the line for 32-bit pointer addresses in ./atb/raw.py
c_pointer = ctypes.c_void_p    # instead of the default 64-bit ctypes.c_ulonglong

I obtain the following error when running

python3 demo-glut.py 

Traceback (most recent call last):
  File "demo-glut.py", line 139, in <module>
    bar.add_var("Trackball/Phi", step=0.5, getter=trackball._get_phi, setter=trackball._set_phi)
  File "/home/pi/AntTweakBar-python/src/build/lib/atb-python/atb/__init__.py", line 725, in add_var
    ctypes.py_object(data), def_str)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type

I reckon that there are some subtle ctypes / typemap changes required between Python 2 and 3 in ./atb/__init__.py that could not be automatically converted using 2to3 and that I could unfortunately not resolve myself. Any confirmation or advice in this regard would be greatly appreciated. Thank you very much indeed!

**Comment by rougier** [comment]
I doubt it will b compatible. As a replacement, I woudl advise to use [pyimgui](https://pyimgui.readthedocs.io/en/latest/guide/first-steps.html) which is based on the amazing [imgui](https://github.com/ocornut/imgui)

**Comment by Inventor-Mentor** [comment]
Thanks for swiftly sharing your advice. pyimgui is most amazing indeed and offers the same (and more) GUI controls for an OpenGL rendering context and supports many more rendering backends besides GLUT.
Best regards and wishes, Peter
